server:
  port: 5555
      
---
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
zuul:
  routes:
    customer-profile:
      path: /customer-profile/**
      service-id: customer-profile
    customer-system:
      path: /customer/**
      service-id: customer-system
    official-system:
      path: /official/**
      service-id: official-system