server:
  port: 1111

---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: loan-system
      
---
eureka:
  instance:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      

