server:
  port: 8087
  context-path: /CustomerProfile
  
---
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: loan-system    

---
HystrixErrorThresholdPercentage: 20
